### ISSUE TITLE
Gaya Penulisan Kode

### ISSUE THREAD

**Issue by jefrydco** [fauzan1892/vuejs-cari-text-video#1]
Hi Mas Fauzan, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Fauzan. Saya ada satu saran terkait gaya penulisan kode yang Mas gunakan.

Saya lihat pada bagian `methods` Mas menggunakan gaya penulisan seperti ini

```javascript
methods: {
  fungsi()
  {
    if(/* Kondisi */)
    {
       // Sesuatu
    }
  }
}
```

Menurut saya gaya penulisan kode JavaScript seperti itu kurang umum Mas, saya sarankan Mas menggunakan gaya penulisan yang umum digunakan oleh pengembang perangkat lunak JavaScript lainnya, seperti berikut:

```javascript
methods: {
  fungsi() {
    if(/* Kondisi */) {
       // Sesuatu
    }
  }
}
```

Walaupun terlihat sepeleh dan keduanya masih bisa di eksekusi dengan baik, menurut saya akan lebih baik jika kita mengikuti aturan gaya penulisan yang telah digunakan oleh pengembang perangkat lunak JavaScript lainnya.

Apalagi jika nanti sudah bekerja dalam tim, gaya penulisan kode yang seragam akan sangat membantu anggota tim lain untuk lebih cepat beradaptasi. Sehingga jika ada orang lain melihat kode yg di tulis oleh tim tersebut, seolah-olah kode tersebut ditulis oleh hanya seorang karena keseragamannya.

Lebih lengkap Mas dapat membaca pada tautan berikut [Mozilla Developer Network - JavaScript guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#Functions_and_objects)

Semangat Mas! 😄

**Comment by fauzan1892** [comment]
Halo juga mas Jefry,  saya jadi tahu adanya aturan gaya penulisan javascript yang baik, karena saya terbiasa menulis php jadi kebawa, Terima kasih atas sarannya Mas, semoga ilmunya berkah dan bermanfaat :smile: :pray:
